// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dronePosVec.proto
// Protobuf C++ Version: 5.29.2

#ifndef dronePosVec_2eproto_2epb_2eh
#define dronePosVec_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_dronePosVec_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_dronePosVec_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_dronePosVec_2eproto;
namespace dronePosVec {
class dataTransfers;
struct dataTransfersDefaultTypeInternal;
extern dataTransfersDefaultTypeInternal _dataTransfers_default_instance_;
class droneControl;
struct droneControlDefaultTypeInternal;
extern droneControlDefaultTypeInternal _droneControl_default_instance_;
class dronePosition;
struct dronePositionDefaultTypeInternal;
extern dronePositionDefaultTypeInternal _dronePosition_default_instance_;
}  // namespace dronePosVec
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace dronePosVec {
enum dataDevices : int {
  IMUonly = 0,
  CameraPos = 1,
  KalmanFilter = 2,
  CameraImgRGB = 3,
  CameraImgDepth = 4,
  dataDevices_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  dataDevices_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool dataDevices_IsValid(int value);
extern const uint32_t dataDevices_internal_data_[];
constexpr dataDevices dataDevices_MIN = static_cast<dataDevices>(0);
constexpr dataDevices dataDevices_MAX = static_cast<dataDevices>(4);
constexpr int dataDevices_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
dataDevices_descriptor();
template <typename T>
const std::string& dataDevices_Name(T value) {
  static_assert(std::is_same<T, dataDevices>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to dataDevices_Name().");
  return dataDevices_Name(static_cast<dataDevices>(value));
}
template <>
inline const std::string& dataDevices_Name(dataDevices value) {
  return ::google::protobuf::internal::NameOfDenseEnum<dataDevices_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool dataDevices_Parse(absl::string_view name, dataDevices* value) {
  return ::google::protobuf::internal::ParseNamedEnum<dataDevices>(
      dataDevices_descriptor(), name, value);
}
enum transferType : int {
  timeSync = 0,
  socketInfo = 1,
  stateChange = 2,
  start = 3,
  end = 4,
  transferType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  transferType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool transferType_IsValid(int value);
extern const uint32_t transferType_internal_data_[];
constexpr transferType transferType_MIN = static_cast<transferType>(0);
constexpr transferType transferType_MAX = static_cast<transferType>(4);
constexpr int transferType_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
transferType_descriptor();
template <typename T>
const std::string& transferType_Name(T value) {
  static_assert(std::is_same<T, transferType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to transferType_Name().");
  return transferType_Name(static_cast<transferType>(value));
}
template <>
inline const std::string& transferType_Name(transferType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<transferType_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool transferType_Parse(absl::string_view name, transferType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<transferType>(
      transferType_descriptor(), name, value);
}
enum progName : int {
  server = 0,
  drone = 1,
  estimator = 2,
  arena = 3,
  camera = 4,
  rl = 5,
  progName_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  progName_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool progName_IsValid(int value);
extern const uint32_t progName_internal_data_[];
constexpr progName progName_MIN = static_cast<progName>(0);
constexpr progName progName_MAX = static_cast<progName>(5);
constexpr int progName_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor*
progName_descriptor();
template <typename T>
const std::string& progName_Name(T value) {
  static_assert(std::is_same<T, progName>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to progName_Name().");
  return progName_Name(static_cast<progName>(value));
}
template <>
inline const std::string& progName_Name(progName value) {
  return ::google::protobuf::internal::NameOfDenseEnum<progName_descriptor,
                                                 0, 5>(
      static_cast<int>(value));
}
inline bool progName_Parse(absl::string_view name, progName* value) {
  return ::google::protobuf::internal::ParseNamedEnum<progName>(
      progName_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class dronePosition final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:dronePosVec.dronePosition) */ {
 public:
  inline dronePosition() : dronePosition(nullptr) {}
  ~dronePosition() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(dronePosition* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(dronePosition));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR dronePosition(
      ::google::protobuf::internal::ConstantInitialized);

  inline dronePosition(const dronePosition& from) : dronePosition(nullptr, from) {}
  inline dronePosition(dronePosition&& from) noexcept
      : dronePosition(nullptr, std::move(from)) {}
  inline dronePosition& operator=(const dronePosition& from) {
    CopyFrom(from);
    return *this;
  }
  inline dronePosition& operator=(dronePosition&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const dronePosition& default_instance() {
    return *internal_default_instance();
  }
  static inline const dronePosition* internal_default_instance() {
    return reinterpret_cast<const dronePosition*>(
        &_dronePosition_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(dronePosition& a, dronePosition& b) { a.Swap(&b); }
  inline void Swap(dronePosition* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(dronePosition* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  dronePosition* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<dronePosition>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const dronePosition& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const dronePosition& from) { dronePosition::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(dronePosition* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "dronePosVec.dronePosition"; }

 protected:
  explicit dronePosition(::google::protobuf::Arena* arena);
  dronePosition(::google::protobuf::Arena* arena, const dronePosition& from);
  dronePosition(::google::protobuf::Arena* arena, dronePosition&& from) noexcept
      : dronePosition(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPosShapeFieldNumber = 2,
    kPositionFieldNumber = 3,
    kRotShapeFieldNumber = 4,
    kRotationFieldNumber = 5,
    kCameraRawFieldNumber = 8,
    kRotation2FieldNumber = 9,
    kDeviceTypeFieldNumber = 1,
    kCamIterationFieldNumber = 7,
    kTimestampNsFieldNumber = 6,
    kDroneBatteryFieldNumber = 10,
  };
  // repeated uint32 posShape = 2 [packed = true];
  int posshape_size() const;
  private:
  int _internal_posshape_size() const;

  public:
  void clear_posshape() ;
  ::uint32_t posshape(int index) const;
  void set_posshape(int index, ::uint32_t value);
  void add_posshape(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& posshape() const;
  ::google::protobuf::RepeatedField<::uint32_t>* mutable_posshape();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_posshape() const;
  ::google::protobuf::RepeatedField<::uint32_t>* _internal_mutable_posshape();

  public:
  // repeated float position = 3 [packed = true];
  int position_size() const;
  private:
  int _internal_position_size() const;

  public:
  void clear_position() ;
  float position(int index) const;
  void set_position(int index, float value);
  void add_position(float value);
  const ::google::protobuf::RepeatedField<float>& position() const;
  ::google::protobuf::RepeatedField<float>* mutable_position();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_position() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_position();

  public:
  // repeated uint32 rotShape = 4 [packed = true];
  int rotshape_size() const;
  private:
  int _internal_rotshape_size() const;

  public:
  void clear_rotshape() ;
  ::uint32_t rotshape(int index) const;
  void set_rotshape(int index, ::uint32_t value);
  void add_rotshape(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& rotshape() const;
  ::google::protobuf::RepeatedField<::uint32_t>* mutable_rotshape();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_rotshape() const;
  ::google::protobuf::RepeatedField<::uint32_t>* _internal_mutable_rotshape();

  public:
  // repeated float rotation = 5 [packed = true];
  int rotation_size() const;
  private:
  int _internal_rotation_size() const;

  public:
  void clear_rotation() ;
  float rotation(int index) const;
  void set_rotation(int index, float value);
  void add_rotation(float value);
  const ::google::protobuf::RepeatedField<float>& rotation() const;
  ::google::protobuf::RepeatedField<float>* mutable_rotation();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_rotation() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_rotation();

  public:
  // repeated uint32 cameraRaw = 8 [packed = true];
  int cameraraw_size() const;
  private:
  int _internal_cameraraw_size() const;

  public:
  void clear_cameraraw() ;
  ::uint32_t cameraraw(int index) const;
  void set_cameraraw(int index, ::uint32_t value);
  void add_cameraraw(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& cameraraw() const;
  ::google::protobuf::RepeatedField<::uint32_t>* mutable_cameraraw();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_cameraraw() const;
  ::google::protobuf::RepeatedField<::uint32_t>* _internal_mutable_cameraraw();

  public:
  // repeated float rotation2 = 9 [packed = true];
  int rotation2_size() const;
  private:
  int _internal_rotation2_size() const;

  public:
  void clear_rotation2() ;
  float rotation2(int index) const;
  void set_rotation2(int index, float value);
  void add_rotation2(float value);
  const ::google::protobuf::RepeatedField<float>& rotation2() const;
  ::google::protobuf::RepeatedField<float>* mutable_rotation2();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_rotation2() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_rotation2();

  public:
  // .dronePosVec.dataDevices deviceType = 1;
  void clear_devicetype() ;
  ::dronePosVec::dataDevices devicetype() const;
  void set_devicetype(::dronePosVec::dataDevices value);

  private:
  ::dronePosVec::dataDevices _internal_devicetype() const;
  void _internal_set_devicetype(::dronePosVec::dataDevices value);

  public:
  // uint32 camIteration = 7;
  void clear_camiteration() ;
  ::uint32_t camiteration() const;
  void set_camiteration(::uint32_t value);

  private:
  ::uint32_t _internal_camiteration() const;
  void _internal_set_camiteration(::uint32_t value);

  public:
  // uint64 timestamp_ns = 6;
  void clear_timestamp_ns() ;
  ::uint64_t timestamp_ns() const;
  void set_timestamp_ns(::uint64_t value);

  private:
  ::uint64_t _internal_timestamp_ns() const;
  void _internal_set_timestamp_ns(::uint64_t value);

  public:
  // float droneBattery = 10;
  void clear_dronebattery() ;
  float dronebattery() const;
  void set_dronebattery(float value);

  private:
  float _internal_dronebattery() const;
  void _internal_set_dronebattery(float value);

  public:
  // @@protoc_insertion_point(class_scope:dronePosVec.dronePosition)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 10, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const dronePosition& from_msg);
    ::google::protobuf::RepeatedField<::uint32_t> posshape_;
    ::google::protobuf::internal::CachedSize _posshape_cached_byte_size_;
    ::google::protobuf::RepeatedField<float> position_;
    ::google::protobuf::RepeatedField<::uint32_t> rotshape_;
    ::google::protobuf::internal::CachedSize _rotshape_cached_byte_size_;
    ::google::protobuf::RepeatedField<float> rotation_;
    ::google::protobuf::RepeatedField<::uint32_t> cameraraw_;
    ::google::protobuf::internal::CachedSize _cameraraw_cached_byte_size_;
    ::google::protobuf::RepeatedField<float> rotation2_;
    int devicetype_;
    ::uint32_t camiteration_;
    ::uint64_t timestamp_ns_;
    float dronebattery_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dronePosVec_2eproto;
};
// -------------------------------------------------------------------

class droneControl final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:dronePosVec.droneControl) */ {
 public:
  inline droneControl() : droneControl(nullptr) {}
  ~droneControl() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(droneControl* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(droneControl));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR droneControl(
      ::google::protobuf::internal::ConstantInitialized);

  inline droneControl(const droneControl& from) : droneControl(nullptr, from) {}
  inline droneControl(droneControl&& from) noexcept
      : droneControl(nullptr, std::move(from)) {}
  inline droneControl& operator=(const droneControl& from) {
    CopyFrom(from);
    return *this;
  }
  inline droneControl& operator=(droneControl&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const droneControl& default_instance() {
    return *internal_default_instance();
  }
  static inline const droneControl* internal_default_instance() {
    return reinterpret_cast<const droneControl*>(
        &_droneControl_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(droneControl& a, droneControl& b) { a.Swap(&b); }
  inline void Swap(droneControl* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(droneControl* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  droneControl* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<droneControl>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const droneControl& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const droneControl& from) { droneControl::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(droneControl* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "dronePosVec.droneControl"; }

 protected:
  explicit droneControl(::google::protobuf::Arena* arena);
  droneControl(::google::protobuf::Arena* arena, const droneControl& from);
  droneControl(::google::protobuf::Arena* arena, droneControl&& from) noexcept
      : droneControl(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMotorFLFieldNumber = 1,
    kMotorFRFieldNumber = 2,
    kMotorBLFieldNumber = 3,
    kMotorBRFieldNumber = 4,
    kKillswitchFieldNumber = 5,
  };
  // float motorFL = 1;
  void clear_motorfl() ;
  float motorfl() const;
  void set_motorfl(float value);

  private:
  float _internal_motorfl() const;
  void _internal_set_motorfl(float value);

  public:
  // float motorFR = 2;
  void clear_motorfr() ;
  float motorfr() const;
  void set_motorfr(float value);

  private:
  float _internal_motorfr() const;
  void _internal_set_motorfr(float value);

  public:
  // float motorBL = 3;
  void clear_motorbl() ;
  float motorbl() const;
  void set_motorbl(float value);

  private:
  float _internal_motorbl() const;
  void _internal_set_motorbl(float value);

  public:
  // float motorBR = 4;
  void clear_motorbr() ;
  float motorbr() const;
  void set_motorbr(float value);

  private:
  float _internal_motorbr() const;
  void _internal_set_motorbr(float value);

  public:
  // bool killswitch = 5;
  void clear_killswitch() ;
  bool killswitch() const;
  void set_killswitch(bool value);

  private:
  bool _internal_killswitch() const;
  void _internal_set_killswitch(bool value);

  public:
  // @@protoc_insertion_point(class_scope:dronePosVec.droneControl)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const droneControl& from_msg);
    float motorfl_;
    float motorfr_;
    float motorbl_;
    float motorbr_;
    bool killswitch_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dronePosVec_2eproto;
};
// -------------------------------------------------------------------

class dataTransfers final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:dronePosVec.dataTransfers) */ {
 public:
  inline dataTransfers() : dataTransfers(nullptr) {}
  ~dataTransfers() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(dataTransfers* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(dataTransfers));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR dataTransfers(
      ::google::protobuf::internal::ConstantInitialized);

  inline dataTransfers(const dataTransfers& from) : dataTransfers(nullptr, from) {}
  inline dataTransfers(dataTransfers&& from) noexcept
      : dataTransfers(nullptr, std::move(from)) {}
  inline dataTransfers& operator=(const dataTransfers& from) {
    CopyFrom(from);
    return *this;
  }
  inline dataTransfers& operator=(dataTransfers&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const dataTransfers& default_instance() {
    return *internal_default_instance();
  }
  static inline const dataTransfers* internal_default_instance() {
    return reinterpret_cast<const dataTransfers*>(
        &_dataTransfers_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(dataTransfers& a, dataTransfers& b) { a.Swap(&b); }
  inline void Swap(dataTransfers* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(dataTransfers* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  dataTransfers* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<dataTransfers>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const dataTransfers& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const dataTransfers& from) { dataTransfers::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(dataTransfers* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "dronePosVec.dataTransfers"; }

 protected:
  explicit dataTransfers(::google::protobuf::Arena* arena);
  dataTransfers(::google::protobuf::Arena* arena, const dataTransfers& from);
  dataTransfers(::google::protobuf::Arena* arena, dataTransfers&& from) noexcept
      : dataTransfers(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMsgFieldNumber = 3,
    kIPFieldNumber = 5,
    kSockaddrFieldNumber = 7,
    kIDFieldNumber = 1,
    kTypeFieldNumber = 2,
    kTimeSyncNsFieldNumber = 4,
    kPortFieldNumber = 6,
    kSockaddrlenFieldNumber = 8,
    kSaFamilyFieldNumber = 9,
  };
  // string msg = 3;
  void clear_msg() ;
  const std::string& msg() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_msg(Arg_&& arg, Args_... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* value);

  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(
      const std::string& value);
  std::string* _internal_mutable_msg();

  public:
  // string IP = 5;
  void clear_ip() ;
  const std::string& ip() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_ip(Arg_&& arg, Args_... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* value);

  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(
      const std::string& value);
  std::string* _internal_mutable_ip();

  public:
  // bytes sockaddr = 7;
  void clear_sockaddr() ;
  const std::string& sockaddr() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sockaddr(Arg_&& arg, Args_... args);
  std::string* mutable_sockaddr();
  PROTOBUF_NODISCARD std::string* release_sockaddr();
  void set_allocated_sockaddr(std::string* value);

  private:
  const std::string& _internal_sockaddr() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sockaddr(
      const std::string& value);
  std::string* _internal_mutable_sockaddr();

  public:
  // .dronePosVec.progName ID = 1;
  void clear_id() ;
  ::dronePosVec::progName id() const;
  void set_id(::dronePosVec::progName value);

  private:
  ::dronePosVec::progName _internal_id() const;
  void _internal_set_id(::dronePosVec::progName value);

  public:
  // .dronePosVec.transferType type = 2;
  void clear_type() ;
  ::dronePosVec::transferType type() const;
  void set_type(::dronePosVec::transferType value);

  private:
  ::dronePosVec::transferType _internal_type() const;
  void _internal_set_type(::dronePosVec::transferType value);

  public:
  // int64 timeSync_ns = 4;
  void clear_timesync_ns() ;
  ::int64_t timesync_ns() const;
  void set_timesync_ns(::int64_t value);

  private:
  ::int64_t _internal_timesync_ns() const;
  void _internal_set_timesync_ns(::int64_t value);

  public:
  // uint32 port = 6;
  void clear_port() ;
  ::uint32_t port() const;
  void set_port(::uint32_t value);

  private:
  ::uint32_t _internal_port() const;
  void _internal_set_port(::uint32_t value);

  public:
  // uint32 sockaddrlen = 8;
  void clear_sockaddrlen() ;
  ::uint32_t sockaddrlen() const;
  void set_sockaddrlen(::uint32_t value);

  private:
  ::uint32_t _internal_sockaddrlen() const;
  void _internal_set_sockaddrlen(::uint32_t value);

  public:
  // uint32 sa_family = 9;
  void clear_sa_family() ;
  ::uint32_t sa_family() const;
  void set_sa_family(::uint32_t value);

  private:
  ::uint32_t _internal_sa_family() const;
  void _internal_set_sa_family(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:dronePosVec.dataTransfers)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 9, 0,
      47, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const dataTransfers& from_msg);
    ::google::protobuf::internal::ArenaStringPtr msg_;
    ::google::protobuf::internal::ArenaStringPtr ip_;
    ::google::protobuf::internal::ArenaStringPtr sockaddr_;
    int id_;
    int type_;
    ::int64_t timesync_ns_;
    ::uint32_t port_;
    ::uint32_t sockaddrlen_;
    ::uint32_t sa_family_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dronePosVec_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// dronePosition

// .dronePosVec.dataDevices deviceType = 1;
inline void dronePosition::clear_devicetype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.devicetype_ = 0;
}
inline ::dronePosVec::dataDevices dronePosition::devicetype() const {
  // @@protoc_insertion_point(field_get:dronePosVec.dronePosition.deviceType)
  return _internal_devicetype();
}
inline void dronePosition::set_devicetype(::dronePosVec::dataDevices value) {
  _internal_set_devicetype(value);
  // @@protoc_insertion_point(field_set:dronePosVec.dronePosition.deviceType)
}
inline ::dronePosVec::dataDevices dronePosition::_internal_devicetype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::dronePosVec::dataDevices>(_impl_.devicetype_);
}
inline void dronePosition::_internal_set_devicetype(::dronePosVec::dataDevices value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.devicetype_ = value;
}

// repeated uint32 posShape = 2 [packed = true];
inline int dronePosition::_internal_posshape_size() const {
  return _internal_posshape().size();
}
inline int dronePosition::posshape_size() const {
  return _internal_posshape_size();
}
inline void dronePosition::clear_posshape() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.posshape_.Clear();
}
inline ::uint32_t dronePosition::posshape(int index) const {
  // @@protoc_insertion_point(field_get:dronePosVec.dronePosition.posShape)
  return _internal_posshape().Get(index);
}
inline void dronePosition::set_posshape(int index, ::uint32_t value) {
  _internal_mutable_posshape()->Set(index, value);
  // @@protoc_insertion_point(field_set:dronePosVec.dronePosition.posShape)
}
inline void dronePosition::add_posshape(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_posshape()->Add(value);
  // @@protoc_insertion_point(field_add:dronePosVec.dronePosition.posShape)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& dronePosition::posshape() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:dronePosVec.dronePosition.posShape)
  return _internal_posshape();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* dronePosition::mutable_posshape()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:dronePosVec.dronePosition.posShape)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_posshape();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
dronePosition::_internal_posshape() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.posshape_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* dronePosition::_internal_mutable_posshape() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.posshape_;
}

// repeated float position = 3 [packed = true];
inline int dronePosition::_internal_position_size() const {
  return _internal_position().size();
}
inline int dronePosition::position_size() const {
  return _internal_position_size();
}
inline void dronePosition::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_.Clear();
}
inline float dronePosition::position(int index) const {
  // @@protoc_insertion_point(field_get:dronePosVec.dronePosition.position)
  return _internal_position().Get(index);
}
inline void dronePosition::set_position(int index, float value) {
  _internal_mutable_position()->Set(index, value);
  // @@protoc_insertion_point(field_set:dronePosVec.dronePosition.position)
}
inline void dronePosition::add_position(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_position()->Add(value);
  // @@protoc_insertion_point(field_add:dronePosVec.dronePosition.position)
}
inline const ::google::protobuf::RepeatedField<float>& dronePosition::position() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:dronePosVec.dronePosition.position)
  return _internal_position();
}
inline ::google::protobuf::RepeatedField<float>* dronePosition::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:dronePosVec.dronePosition.position)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_position();
}
inline const ::google::protobuf::RepeatedField<float>&
dronePosition::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_;
}
inline ::google::protobuf::RepeatedField<float>* dronePosition::_internal_mutable_position() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.position_;
}

// repeated uint32 rotShape = 4 [packed = true];
inline int dronePosition::_internal_rotshape_size() const {
  return _internal_rotshape().size();
}
inline int dronePosition::rotshape_size() const {
  return _internal_rotshape_size();
}
inline void dronePosition::clear_rotshape() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rotshape_.Clear();
}
inline ::uint32_t dronePosition::rotshape(int index) const {
  // @@protoc_insertion_point(field_get:dronePosVec.dronePosition.rotShape)
  return _internal_rotshape().Get(index);
}
inline void dronePosition::set_rotshape(int index, ::uint32_t value) {
  _internal_mutable_rotshape()->Set(index, value);
  // @@protoc_insertion_point(field_set:dronePosVec.dronePosition.rotShape)
}
inline void dronePosition::add_rotshape(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_rotshape()->Add(value);
  // @@protoc_insertion_point(field_add:dronePosVec.dronePosition.rotShape)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& dronePosition::rotshape() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:dronePosVec.dronePosition.rotShape)
  return _internal_rotshape();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* dronePosition::mutable_rotshape()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:dronePosVec.dronePosition.rotShape)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rotshape();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
dronePosition::_internal_rotshape() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rotshape_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* dronePosition::_internal_mutable_rotshape() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rotshape_;
}

// repeated float rotation = 5 [packed = true];
inline int dronePosition::_internal_rotation_size() const {
  return _internal_rotation().size();
}
inline int dronePosition::rotation_size() const {
  return _internal_rotation_size();
}
inline void dronePosition::clear_rotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rotation_.Clear();
}
inline float dronePosition::rotation(int index) const {
  // @@protoc_insertion_point(field_get:dronePosVec.dronePosition.rotation)
  return _internal_rotation().Get(index);
}
inline void dronePosition::set_rotation(int index, float value) {
  _internal_mutable_rotation()->Set(index, value);
  // @@protoc_insertion_point(field_set:dronePosVec.dronePosition.rotation)
}
inline void dronePosition::add_rotation(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_rotation()->Add(value);
  // @@protoc_insertion_point(field_add:dronePosVec.dronePosition.rotation)
}
inline const ::google::protobuf::RepeatedField<float>& dronePosition::rotation() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:dronePosVec.dronePosition.rotation)
  return _internal_rotation();
}
inline ::google::protobuf::RepeatedField<float>* dronePosition::mutable_rotation()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:dronePosVec.dronePosition.rotation)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rotation();
}
inline const ::google::protobuf::RepeatedField<float>&
dronePosition::_internal_rotation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rotation_;
}
inline ::google::protobuf::RepeatedField<float>* dronePosition::_internal_mutable_rotation() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rotation_;
}

// uint64 timestamp_ns = 6;
inline void dronePosition::clear_timestamp_ns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ns_ = ::uint64_t{0u};
}
inline ::uint64_t dronePosition::timestamp_ns() const {
  // @@protoc_insertion_point(field_get:dronePosVec.dronePosition.timestamp_ns)
  return _internal_timestamp_ns();
}
inline void dronePosition::set_timestamp_ns(::uint64_t value) {
  _internal_set_timestamp_ns(value);
  // @@protoc_insertion_point(field_set:dronePosVec.dronePosition.timestamp_ns)
}
inline ::uint64_t dronePosition::_internal_timestamp_ns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ns_;
}
inline void dronePosition::_internal_set_timestamp_ns(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ns_ = value;
}

// uint32 camIteration = 7;
inline void dronePosition::clear_camiteration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.camiteration_ = 0u;
}
inline ::uint32_t dronePosition::camiteration() const {
  // @@protoc_insertion_point(field_get:dronePosVec.dronePosition.camIteration)
  return _internal_camiteration();
}
inline void dronePosition::set_camiteration(::uint32_t value) {
  _internal_set_camiteration(value);
  // @@protoc_insertion_point(field_set:dronePosVec.dronePosition.camIteration)
}
inline ::uint32_t dronePosition::_internal_camiteration() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.camiteration_;
}
inline void dronePosition::_internal_set_camiteration(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.camiteration_ = value;
}

// repeated uint32 cameraRaw = 8 [packed = true];
inline int dronePosition::_internal_cameraraw_size() const {
  return _internal_cameraraw().size();
}
inline int dronePosition::cameraraw_size() const {
  return _internal_cameraraw_size();
}
inline void dronePosition::clear_cameraraw() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cameraraw_.Clear();
}
inline ::uint32_t dronePosition::cameraraw(int index) const {
  // @@protoc_insertion_point(field_get:dronePosVec.dronePosition.cameraRaw)
  return _internal_cameraraw().Get(index);
}
inline void dronePosition::set_cameraraw(int index, ::uint32_t value) {
  _internal_mutable_cameraraw()->Set(index, value);
  // @@protoc_insertion_point(field_set:dronePosVec.dronePosition.cameraRaw)
}
inline void dronePosition::add_cameraraw(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_cameraraw()->Add(value);
  // @@protoc_insertion_point(field_add:dronePosVec.dronePosition.cameraRaw)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& dronePosition::cameraraw() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:dronePosVec.dronePosition.cameraRaw)
  return _internal_cameraraw();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* dronePosition::mutable_cameraraw()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:dronePosVec.dronePosition.cameraRaw)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_cameraraw();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
dronePosition::_internal_cameraraw() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cameraraw_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* dronePosition::_internal_mutable_cameraraw() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.cameraraw_;
}

// repeated float rotation2 = 9 [packed = true];
inline int dronePosition::_internal_rotation2_size() const {
  return _internal_rotation2().size();
}
inline int dronePosition::rotation2_size() const {
  return _internal_rotation2_size();
}
inline void dronePosition::clear_rotation2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rotation2_.Clear();
}
inline float dronePosition::rotation2(int index) const {
  // @@protoc_insertion_point(field_get:dronePosVec.dronePosition.rotation2)
  return _internal_rotation2().Get(index);
}
inline void dronePosition::set_rotation2(int index, float value) {
  _internal_mutable_rotation2()->Set(index, value);
  // @@protoc_insertion_point(field_set:dronePosVec.dronePosition.rotation2)
}
inline void dronePosition::add_rotation2(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_rotation2()->Add(value);
  // @@protoc_insertion_point(field_add:dronePosVec.dronePosition.rotation2)
}
inline const ::google::protobuf::RepeatedField<float>& dronePosition::rotation2() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:dronePosVec.dronePosition.rotation2)
  return _internal_rotation2();
}
inline ::google::protobuf::RepeatedField<float>* dronePosition::mutable_rotation2()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:dronePosVec.dronePosition.rotation2)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rotation2();
}
inline const ::google::protobuf::RepeatedField<float>&
dronePosition::_internal_rotation2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rotation2_;
}
inline ::google::protobuf::RepeatedField<float>* dronePosition::_internal_mutable_rotation2() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rotation2_;
}

// float droneBattery = 10;
inline void dronePosition::clear_dronebattery() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dronebattery_ = 0;
}
inline float dronePosition::dronebattery() const {
  // @@protoc_insertion_point(field_get:dronePosVec.dronePosition.droneBattery)
  return _internal_dronebattery();
}
inline void dronePosition::set_dronebattery(float value) {
  _internal_set_dronebattery(value);
  // @@protoc_insertion_point(field_set:dronePosVec.dronePosition.droneBattery)
}
inline float dronePosition::_internal_dronebattery() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dronebattery_;
}
inline void dronePosition::_internal_set_dronebattery(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dronebattery_ = value;
}

// -------------------------------------------------------------------

// droneControl

// float motorFL = 1;
inline void droneControl::clear_motorfl() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motorfl_ = 0;
}
inline float droneControl::motorfl() const {
  // @@protoc_insertion_point(field_get:dronePosVec.droneControl.motorFL)
  return _internal_motorfl();
}
inline void droneControl::set_motorfl(float value) {
  _internal_set_motorfl(value);
  // @@protoc_insertion_point(field_set:dronePosVec.droneControl.motorFL)
}
inline float droneControl::_internal_motorfl() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.motorfl_;
}
inline void droneControl::_internal_set_motorfl(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motorfl_ = value;
}

// float motorFR = 2;
inline void droneControl::clear_motorfr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motorfr_ = 0;
}
inline float droneControl::motorfr() const {
  // @@protoc_insertion_point(field_get:dronePosVec.droneControl.motorFR)
  return _internal_motorfr();
}
inline void droneControl::set_motorfr(float value) {
  _internal_set_motorfr(value);
  // @@protoc_insertion_point(field_set:dronePosVec.droneControl.motorFR)
}
inline float droneControl::_internal_motorfr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.motorfr_;
}
inline void droneControl::_internal_set_motorfr(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motorfr_ = value;
}

// float motorBL = 3;
inline void droneControl::clear_motorbl() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motorbl_ = 0;
}
inline float droneControl::motorbl() const {
  // @@protoc_insertion_point(field_get:dronePosVec.droneControl.motorBL)
  return _internal_motorbl();
}
inline void droneControl::set_motorbl(float value) {
  _internal_set_motorbl(value);
  // @@protoc_insertion_point(field_set:dronePosVec.droneControl.motorBL)
}
inline float droneControl::_internal_motorbl() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.motorbl_;
}
inline void droneControl::_internal_set_motorbl(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motorbl_ = value;
}

// float motorBR = 4;
inline void droneControl::clear_motorbr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motorbr_ = 0;
}
inline float droneControl::motorbr() const {
  // @@protoc_insertion_point(field_get:dronePosVec.droneControl.motorBR)
  return _internal_motorbr();
}
inline void droneControl::set_motorbr(float value) {
  _internal_set_motorbr(value);
  // @@protoc_insertion_point(field_set:dronePosVec.droneControl.motorBR)
}
inline float droneControl::_internal_motorbr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.motorbr_;
}
inline void droneControl::_internal_set_motorbr(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motorbr_ = value;
}

// bool killswitch = 5;
inline void droneControl::clear_killswitch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.killswitch_ = false;
}
inline bool droneControl::killswitch() const {
  // @@protoc_insertion_point(field_get:dronePosVec.droneControl.killswitch)
  return _internal_killswitch();
}
inline void droneControl::set_killswitch(bool value) {
  _internal_set_killswitch(value);
  // @@protoc_insertion_point(field_set:dronePosVec.droneControl.killswitch)
}
inline bool droneControl::_internal_killswitch() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.killswitch_;
}
inline void droneControl::_internal_set_killswitch(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.killswitch_ = value;
}

// -------------------------------------------------------------------

// dataTransfers

// .dronePosVec.progName ID = 1;
inline void dataTransfers::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
}
inline ::dronePosVec::progName dataTransfers::id() const {
  // @@protoc_insertion_point(field_get:dronePosVec.dataTransfers.ID)
  return _internal_id();
}
inline void dataTransfers::set_id(::dronePosVec::progName value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:dronePosVec.dataTransfers.ID)
}
inline ::dronePosVec::progName dataTransfers::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::dronePosVec::progName>(_impl_.id_);
}
inline void dataTransfers::_internal_set_id(::dronePosVec::progName value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// .dronePosVec.transferType type = 2;
inline void dataTransfers::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::dronePosVec::transferType dataTransfers::type() const {
  // @@protoc_insertion_point(field_get:dronePosVec.dataTransfers.type)
  return _internal_type();
}
inline void dataTransfers::set_type(::dronePosVec::transferType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:dronePosVec.dataTransfers.type)
}
inline ::dronePosVec::transferType dataTransfers::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::dronePosVec::transferType>(_impl_.type_);
}
inline void dataTransfers::_internal_set_type(::dronePosVec::transferType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// string msg = 3;
inline void dataTransfers::clear_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& dataTransfers::msg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dronePosVec.dataTransfers.msg)
  return _internal_msg();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void dataTransfers::set_msg(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:dronePosVec.dataTransfers.msg)
}
inline std::string* dataTransfers::mutable_msg() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:dronePosVec.dataTransfers.msg)
  return _s;
}
inline const std::string& dataTransfers::_internal_msg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msg_.Get();
}
inline void dataTransfers::_internal_set_msg(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.Set(value, GetArena());
}
inline std::string* dataTransfers::_internal_mutable_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.msg_.Mutable( GetArena());
}
inline std::string* dataTransfers::release_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:dronePosVec.dataTransfers.msg)
  return _impl_.msg_.Release();
}
inline void dataTransfers::set_allocated_msg(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:dronePosVec.dataTransfers.msg)
}

// int64 timeSync_ns = 4;
inline void dataTransfers::clear_timesync_ns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timesync_ns_ = ::int64_t{0};
}
inline ::int64_t dataTransfers::timesync_ns() const {
  // @@protoc_insertion_point(field_get:dronePosVec.dataTransfers.timeSync_ns)
  return _internal_timesync_ns();
}
inline void dataTransfers::set_timesync_ns(::int64_t value) {
  _internal_set_timesync_ns(value);
  // @@protoc_insertion_point(field_set:dronePosVec.dataTransfers.timeSync_ns)
}
inline ::int64_t dataTransfers::_internal_timesync_ns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timesync_ns_;
}
inline void dataTransfers::_internal_set_timesync_ns(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timesync_ns_ = value;
}

// string IP = 5;
inline void dataTransfers::clear_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.ClearToEmpty();
}
inline const std::string& dataTransfers::ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dronePosVec.dataTransfers.IP)
  return _internal_ip();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void dataTransfers::set_ip(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:dronePosVec.dataTransfers.IP)
}
inline std::string* dataTransfers::mutable_ip() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:dronePosVec.dataTransfers.IP)
  return _s;
}
inline const std::string& dataTransfers::_internal_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ip_.Get();
}
inline void dataTransfers::_internal_set_ip(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.Set(value, GetArena());
}
inline std::string* dataTransfers::_internal_mutable_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ip_.Mutable( GetArena());
}
inline std::string* dataTransfers::release_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:dronePosVec.dataTransfers.IP)
  return _impl_.ip_.Release();
}
inline void dataTransfers::set_allocated_ip(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ip_.IsDefault()) {
    _impl_.ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:dronePosVec.dataTransfers.IP)
}

// uint32 port = 6;
inline void dataTransfers::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0u;
}
inline ::uint32_t dataTransfers::port() const {
  // @@protoc_insertion_point(field_get:dronePosVec.dataTransfers.port)
  return _internal_port();
}
inline void dataTransfers::set_port(::uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:dronePosVec.dataTransfers.port)
}
inline ::uint32_t dataTransfers::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void dataTransfers::_internal_set_port(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// bytes sockaddr = 7;
inline void dataTransfers::clear_sockaddr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sockaddr_.ClearToEmpty();
}
inline const std::string& dataTransfers::sockaddr() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dronePosVec.dataTransfers.sockaddr)
  return _internal_sockaddr();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void dataTransfers::set_sockaddr(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sockaddr_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:dronePosVec.dataTransfers.sockaddr)
}
inline std::string* dataTransfers::mutable_sockaddr() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sockaddr();
  // @@protoc_insertion_point(field_mutable:dronePosVec.dataTransfers.sockaddr)
  return _s;
}
inline const std::string& dataTransfers::_internal_sockaddr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sockaddr_.Get();
}
inline void dataTransfers::_internal_set_sockaddr(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sockaddr_.Set(value, GetArena());
}
inline std::string* dataTransfers::_internal_mutable_sockaddr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sockaddr_.Mutable( GetArena());
}
inline std::string* dataTransfers::release_sockaddr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:dronePosVec.dataTransfers.sockaddr)
  return _impl_.sockaddr_.Release();
}
inline void dataTransfers::set_allocated_sockaddr(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sockaddr_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sockaddr_.IsDefault()) {
    _impl_.sockaddr_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:dronePosVec.dataTransfers.sockaddr)
}

// uint32 sockaddrlen = 8;
inline void dataTransfers::clear_sockaddrlen() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sockaddrlen_ = 0u;
}
inline ::uint32_t dataTransfers::sockaddrlen() const {
  // @@protoc_insertion_point(field_get:dronePosVec.dataTransfers.sockaddrlen)
  return _internal_sockaddrlen();
}
inline void dataTransfers::set_sockaddrlen(::uint32_t value) {
  _internal_set_sockaddrlen(value);
  // @@protoc_insertion_point(field_set:dronePosVec.dataTransfers.sockaddrlen)
}
inline ::uint32_t dataTransfers::_internal_sockaddrlen() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sockaddrlen_;
}
inline void dataTransfers::_internal_set_sockaddrlen(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sockaddrlen_ = value;
}

// uint32 sa_family = 9;
inline void dataTransfers::clear_sa_family() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sa_family_ = 0u;
}
inline ::uint32_t dataTransfers::sa_family() const {
  // @@protoc_insertion_point(field_get:dronePosVec.dataTransfers.sa_family)
  return _internal_sa_family();
}
inline void dataTransfers::set_sa_family(::uint32_t value) {
  _internal_set_sa_family(value);
  // @@protoc_insertion_point(field_set:dronePosVec.dataTransfers.sa_family)
}
inline ::uint32_t dataTransfers::_internal_sa_family() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sa_family_;
}
inline void dataTransfers::_internal_set_sa_family(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sa_family_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace dronePosVec


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::dronePosVec::dataDevices> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::dronePosVec::dataDevices>() {
  return ::dronePosVec::dataDevices_descriptor();
}
template <>
struct is_proto_enum<::dronePosVec::transferType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::dronePosVec::transferType>() {
  return ::dronePosVec::transferType_descriptor();
}
template <>
struct is_proto_enum<::dronePosVec::progName> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::dronePosVec::progName>() {
  return ::dronePosVec::progName_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // dronePosVec_2eproto_2epb_2eh
